using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HangMan.Infrastructure.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Players",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Players", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Words",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Value = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Words", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Games",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    SecretWord = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    PlayerId = table.Column<int>(type: "int", nullable: false),
                    Status = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Games", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Games_Players_PlayerId",
                        column: x => x.PlayerId,
                        principalTable: "Players",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Guesses",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    GameId = table.Column<int>(type: "int", nullable: false),
                    Letter = table.Column<string>(type: "nvarchar(1)", nullable: false),
                    IsRightGuess = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Guesses", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Guesses_Games_GameId",
                        column: x => x.GameId,
                        principalTable: "Games",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Players",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Mario" },
                    { 2, "Luigi" },
                    { 3, "Peach" },
                    { 4, "Daisy" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 1, "able" },
                    { 2, "about" },
                    { 3, "account" },
                    { 4, "acid" },
                    { 5, "across" },
                    { 6, "act" },
                    { 7, "addition" },
                    { 8, "adjustment" },
                    { 9, "advertisement" },
                    { 10, "after" },
                    { 11, "again" },
                    { 12, "against" },
                    { 13, "agreement" },
                    { 14, "air" },
                    { 15, "all" },
                    { 16, "almost" },
                    { 17, "among" },
                    { 18, "amount" },
                    { 19, "amusement" },
                    { 20, "and" },
                    { 21, "angle" },
                    { 22, "angry" },
                    { 23, "animal" },
                    { 24, "answer" },
                    { 25, "ant" },
                    { 26, "any" },
                    { 27, "apparatus" },
                    { 28, "apple" },
                    { 29, "approval" },
                    { 30, "arch" },
                    { 31, "argument" },
                    { 32, "arm" },
                    { 33, "army" },
                    { 34, "art" },
                    { 35, "as" },
                    { 36, "at" },
                    { 37, "attack" },
                    { 38, "attempt" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 39, "attention" },
                    { 40, "attraction" },
                    { 41, "authority" },
                    { 42, "automatic" },
                    { 43, "awake" },
                    { 44, "baby" },
                    { 45, "back" },
                    { 46, "bad" },
                    { 47, "bag" },
                    { 48, "balance" },
                    { 49, "ball" },
                    { 50, "band" },
                    { 51, "base" },
                    { 52, "basin" },
                    { 53, "basket" },
                    { 54, "bath" },
                    { 55, "be" },
                    { 56, "beautiful" },
                    { 57, "because" },
                    { 58, "bed" },
                    { 59, "bee" },
                    { 60, "before" },
                    { 61, "behaviour" },
                    { 62, "belief" },
                    { 63, "bell" },
                    { 64, "bent" },
                    { 65, "berry" },
                    { 66, "between" },
                    { 67, "bird" },
                    { 68, "birth" },
                    { 69, "bit" },
                    { 70, "bite" },
                    { 71, "bitter" },
                    { 72, "black" },
                    { 73, "blade" },
                    { 74, "blood" },
                    { 75, "blow" },
                    { 76, "blue" },
                    { 77, "board" },
                    { 78, "boat" },
                    { 79, "body" },
                    { 80, "boiling" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 81, "bone" },
                    { 82, "book" },
                    { 83, "boot" },
                    { 84, "bottle" },
                    { 85, "box" },
                    { 86, "boy" },
                    { 87, "brain" },
                    { 88, "brake" },
                    { 89, "branch" },
                    { 90, "brass" },
                    { 91, "bread" },
                    { 92, "breath" },
                    { 93, "brick" },
                    { 94, "bridge" },
                    { 95, "bright" },
                    { 96, "broken" },
                    { 97, "brother" },
                    { 98, "brown" },
                    { 99, "brush" },
                    { 100, "bucket" },
                    { 101, "building" },
                    { 102, "bulb" },
                    { 103, "burn" },
                    { 104, "burst" },
                    { 105, "business" },
                    { 106, "but" },
                    { 107, "butter" },
                    { 108, "button" },
                    { 109, "by" },
                    { 110, "cake" },
                    { 111, "camera" },
                    { 112, "canvas" },
                    { 113, "card" },
                    { 114, "care" },
                    { 115, "carriage" },
                    { 116, "cart" },
                    { 117, "cat" },
                    { 118, "cause" },
                    { 119, "certain" },
                    { 120, "chain" },
                    { 121, "chalk" },
                    { 122, "chance" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 123, "change" },
                    { 124, "cheap" },
                    { 125, "cheese" },
                    { 126, "chemical" },
                    { 127, "chest" },
                    { 128, "chief" },
                    { 129, "chin" },
                    { 130, "church" },
                    { 131, "circle" },
                    { 132, "clean" },
                    { 133, "clear" },
                    { 134, "clock" },
                    { 135, "cloth" },
                    { 136, "cloud" },
                    { 137, "coal" },
                    { 138, "coat" },
                    { 139, "cold" },
                    { 140, "collar" },
                    { 141, "colour" },
                    { 142, "comb" },
                    { 143, "come" },
                    { 144, "comfort" },
                    { 145, "committee" },
                    { 146, "common" },
                    { 147, "company" },
                    { 148, "comparison" },
                    { 149, "competition" },
                    { 150, "complete" },
                    { 151, "complex" },
                    { 152, "condition" },
                    { 153, "connection" },
                    { 154, "conscious" },
                    { 155, "control" },
                    { 156, "cook" },
                    { 157, "copper" },
                    { 158, "copy" },
                    { 159, "cord" },
                    { 160, "cork" },
                    { 161, "cotton" },
                    { 162, "cough" },
                    { 163, "country" },
                    { 164, "cover" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 165, "cow" },
                    { 166, "crack" },
                    { 167, "credit" },
                    { 168, "crime" },
                    { 169, "cruel" },
                    { 170, "crush" },
                    { 171, "cry" },
                    { 172, "cup" },
                    { 173, "current" },
                    { 174, "curtain" },
                    { 175, "curve" },
                    { 176, "cushion" },
                    { 177, "damage" },
                    { 178, "danger" },
                    { 179, "dark" },
                    { 180, "daughter" },
                    { 181, "day" },
                    { 182, "dead" },
                    { 183, "dear" },
                    { 184, "death" },
                    { 185, "debt" },
                    { 186, "decision" },
                    { 187, "deep" },
                    { 188, "degree" },
                    { 189, "delicate" },
                    { 190, "dependent" },
                    { 191, "design" },
                    { 192, "desire" },
                    { 193, "destruction" },
                    { 194, "detail" },
                    { 195, "development" },
                    { 196, "different" },
                    { 197, "digestion" },
                    { 198, "direction" },
                    { 199, "dirty" },
                    { 200, "discovery" },
                    { 201, "discussion" },
                    { 202, "disease" },
                    { 203, "disgust" },
                    { 204, "distance" },
                    { 205, "distribution" },
                    { 206, "division" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 207, "do" },
                    { 208, "dog" },
                    { 209, "door" },
                    { 210, "doubt" },
                    { 211, "down" },
                    { 212, "drain" },
                    { 213, "drawer" },
                    { 214, "dress" },
                    { 215, "drink" },
                    { 216, "driving" },
                    { 217, "drop" },
                    { 218, "dry" },
                    { 219, "dust" },
                    { 220, "ear" },
                    { 221, "early" },
                    { 222, "earth" },
                    { 223, "east" },
                    { 224, "edge" },
                    { 225, "education" },
                    { 226, "effect" },
                    { 227, "egg" },
                    { 228, "elastic" },
                    { 229, "electric" },
                    { 230, "end" },
                    { 231, "engine" },
                    { 232, "enough" },
                    { 233, "equal" },
                    { 234, "error" },
                    { 235, "even" },
                    { 236, "event" },
                    { 237, "ever" },
                    { 238, "every" },
                    { 239, "example" },
                    { 240, "exchange" },
                    { 241, "existence" },
                    { 242, "expansion" },
                    { 243, "experience" },
                    { 244, "expert" },
                    { 245, "eye" },
                    { 246, "face" },
                    { 247, "fact" },
                    { 248, "fall" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 249, "false" },
                    { 250, "family" },
                    { 251, "far" },
                    { 252, "farm" },
                    { 253, "fat" },
                    { 254, "father" },
                    { 255, "fear" },
                    { 256, "feather" },
                    { 257, "feeble" },
                    { 258, "feeling" },
                    { 259, "female" },
                    { 260, "fertile" },
                    { 261, "fiction" },
                    { 262, "field" },
                    { 263, "fight" },
                    { 264, "finger" },
                    { 265, "fire" },
                    { 266, "first" },
                    { 267, "fish" },
                    { 268, "fixed" },
                    { 269, "flag" },
                    { 270, "flame" },
                    { 271, "flat" },
                    { 272, "flight" },
                    { 273, "floor" },
                    { 274, "flower" },
                    { 275, "fly" },
                    { 276, "fold" },
                    { 277, "food" },
                    { 278, "foolish" },
                    { 279, "foot" },
                    { 280, "for" },
                    { 281, "force" },
                    { 282, "fork" },
                    { 283, "form" },
                    { 284, "forward" },
                    { 285, "fowl" },
                    { 286, "frame" },
                    { 287, "free" },
                    { 288, "frequent" },
                    { 289, "friend" },
                    { 290, "from" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 291, "front" },
                    { 292, "fruit" },
                    { 293, "full" },
                    { 294, "future" },
                    { 295, "garden" },
                    { 296, "general" },
                    { 297, "get" },
                    { 298, "girl" },
                    { 299, "give" },
                    { 300, "glass" },
                    { 301, "glove" },
                    { 302, "go" },
                    { 303, "goat" },
                    { 304, "gold" },
                    { 305, "good" },
                    { 306, "government" },
                    { 307, "grain" },
                    { 308, "grass" },
                    { 309, "great" },
                    { 310, "green" },
                    { 311, "grey" },
                    { 312, "grip" },
                    { 313, "group" },
                    { 314, "growth" },
                    { 315, "guide" },
                    { 316, "gun" },
                    { 317, "hair" },
                    { 318, "hammer" },
                    { 319, "hand" },
                    { 320, "hanging" },
                    { 321, "happy" },
                    { 322, "harbour" },
                    { 323, "hard" },
                    { 324, "harmony" },
                    { 325, "hat" },
                    { 326, "hate" },
                    { 327, "have" },
                    { 328, "he" },
                    { 329, "head" },
                    { 330, "healthy" },
                    { 331, "hear" },
                    { 332, "hearing" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 333, "heart" },
                    { 334, "heat" },
                    { 335, "help" },
                    { 336, "high" },
                    { 337, "history" },
                    { 338, "hole" },
                    { 339, "hollow" },
                    { 340, "hook" },
                    { 341, "hope" },
                    { 342, "horn" },
                    { 343, "horse" },
                    { 344, "hospital" },
                    { 345, "hour" },
                    { 346, "house" },
                    { 347, "how" },
                    { 348, "humour" },
                    { 349, "i" },
                    { 350, "ice" },
                    { 351, "idea" },
                    { 352, "if" },
                    { 353, "ill" },
                    { 354, "important" },
                    { 355, "impulse" },
                    { 356, "in" },
                    { 357, "increase" },
                    { 358, "industry" },
                    { 359, "ink" },
                    { 360, "insect" },
                    { 361, "instrument" },
                    { 362, "insurance" },
                    { 363, "interest" },
                    { 364, "invention" },
                    { 365, "iron" },
                    { 366, "island" },
                    { 367, "jelly" },
                    { 368, "jewel" },
                    { 369, "join" },
                    { 370, "journey" },
                    { 371, "judge" },
                    { 372, "jump" },
                    { 373, "keep" },
                    { 374, "kettle" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 375, "key" },
                    { 376, "kick" },
                    { 377, "kind" },
                    { 378, "kiss" },
                    { 379, "knee" },
                    { 380, "knife" },
                    { 381, "knot" },
                    { 382, "knowledge" },
                    { 383, "land" },
                    { 384, "language" },
                    { 385, "last" },
                    { 386, "late" },
                    { 387, "laugh" },
                    { 388, "law" },
                    { 389, "lead" },
                    { 390, "leaf" },
                    { 391, "learning" },
                    { 392, "leather" },
                    { 393, "left" },
                    { 394, "leg" },
                    { 395, "let" },
                    { 396, "letter" },
                    { 397, "level" },
                    { 398, "library" },
                    { 399, "lift" },
                    { 400, "light" },
                    { 401, "like" },
                    { 402, "limit" },
                    { 403, "line" },
                    { 404, "linen" },
                    { 405, "lip" },
                    { 406, "liquid" },
                    { 407, "list" },
                    { 408, "little" },
                    { 409, "living" },
                    { 410, "lock" },
                    { 411, "long" },
                    { 412, "look" },
                    { 413, "loose" },
                    { 414, "loss" },
                    { 415, "loud" },
                    { 416, "love" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 417, "low" },
                    { 418, "machine" },
                    { 419, "make" },
                    { 420, "male" },
                    { 421, "man" },
                    { 422, "manager" },
                    { 423, "map" },
                    { 424, "mark" },
                    { 425, "market" },
                    { 426, "married" },
                    { 427, "mass" },
                    { 428, "match" },
                    { 429, "material" },
                    { 430, "may" },
                    { 431, "meal" },
                    { 432, "measure" },
                    { 433, "meat" },
                    { 434, "medical" },
                    { 435, "meeting" },
                    { 436, "memory" },
                    { 437, "metal" },
                    { 438, "middle" },
                    { 439, "military" },
                    { 440, "milk" },
                    { 441, "mind" },
                    { 442, "mine" },
                    { 443, "minute" },
                    { 444, "mist" },
                    { 445, "mixed" },
                    { 446, "money" },
                    { 447, "monkey" },
                    { 448, "month" },
                    { 449, "moon" },
                    { 450, "morning" },
                    { 451, "mother" },
                    { 452, "motion" },
                    { 453, "mountain" },
                    { 454, "mouth" },
                    { 455, "move" },
                    { 456, "much" },
                    { 457, "muscle" },
                    { 458, "music" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 459, "nail" },
                    { 460, "name" },
                    { 461, "narrow" },
                    { 462, "nation" },
                    { 463, "natural" },
                    { 464, "near" },
                    { 465, "necessary" },
                    { 466, "neck" },
                    { 467, "need" },
                    { 468, "needle" },
                    { 469, "nerve" },
                    { 470, "net" },
                    { 471, "new" },
                    { 472, "news" },
                    { 473, "night" },
                    { 474, "no" },
                    { 475, "noise" },
                    { 476, "normal" },
                    { 477, "north" },
                    { 478, "nose" },
                    { 479, "not" },
                    { 480, "note" },
                    { 481, "now" },
                    { 482, "number" },
                    { 483, "nut" },
                    { 484, "observation" },
                    { 485, "of" },
                    { 486, "off" },
                    { 487, "offer" },
                    { 488, "office" },
                    { 489, "oil" },
                    { 490, "old" },
                    { 491, "on" },
                    { 492, "only" },
                    { 493, "open" },
                    { 494, "operation" },
                    { 495, "opinion" },
                    { 496, "opposite" },
                    { 497, "or" },
                    { 498, "orange" },
                    { 499, "order" },
                    { 500, "organization" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 501, "ornament" },
                    { 502, "other" },
                    { 503, "out" },
                    { 504, "oven" },
                    { 505, "over" },
                    { 506, "owner" },
                    { 507, "page" },
                    { 508, "pain" },
                    { 509, "paint" },
                    { 510, "paper" },
                    { 511, "parallel" },
                    { 512, "parcel" },
                    { 513, "part" },
                    { 514, "past" },
                    { 515, "paste" },
                    { 516, "payment" },
                    { 517, "peace" },
                    { 518, "pen" },
                    { 519, "pencil" },
                    { 520, "person" },
                    { 521, "physical" },
                    { 522, "picture" },
                    { 523, "pig" },
                    { 524, "pin" },
                    { 525, "pipe" },
                    { 526, "place" },
                    { 527, "plane" },
                    { 528, "plant" },
                    { 529, "plate" },
                    { 530, "play" },
                    { 531, "please" },
                    { 532, "pleasure" },
                    { 533, "plough" },
                    { 534, "pocket" },
                    { 535, "point" },
                    { 536, "poison" },
                    { 537, "polish" },
                    { 538, "political" },
                    { 539, "poor" },
                    { 540, "porter" },
                    { 541, "position" },
                    { 542, "possible" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 543, "pot" },
                    { 544, "potato" },
                    { 545, "powder" },
                    { 546, "power" },
                    { 547, "present" },
                    { 548, "price" },
                    { 549, "print" },
                    { 550, "prison" },
                    { 551, "private" },
                    { 552, "probable" },
                    { 553, "process" },
                    { 554, "produce" },
                    { 555, "profit" },
                    { 556, "property" },
                    { 557, "prose" },
                    { 558, "protest" },
                    { 559, "public" },
                    { 560, "pull" },
                    { 561, "pump" },
                    { 562, "punishment" },
                    { 563, "purpose" },
                    { 564, "push" },
                    { 565, "put" },
                    { 566, "quality" },
                    { 567, "question" },
                    { 568, "quick" },
                    { 569, "quiet" },
                    { 570, "quite" },
                    { 571, "rail" },
                    { 572, "rain" },
                    { 573, "range" },
                    { 574, "rat" },
                    { 575, "rate" },
                    { 576, "ray" },
                    { 577, "reaction" },
                    { 578, "reading" },
                    { 579, "ready" },
                    { 580, "reason" },
                    { 581, "receipt" },
                    { 582, "record" },
                    { 583, "red" },
                    { 584, "regret" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 585, "regular" },
                    { 586, "relation" },
                    { 587, "religion" },
                    { 588, "representative" },
                    { 589, "request" },
                    { 590, "respect" },
                    { 591, "responsible" },
                    { 592, "rest" },
                    { 593, "reward" },
                    { 594, "rhythm" },
                    { 595, "rice" },
                    { 596, "right" },
                    { 597, "ring" },
                    { 598, "river" },
                    { 599, "road" },
                    { 600, "rod" },
                    { 601, "roll" },
                    { 602, "roof" },
                    { 603, "room" },
                    { 604, "root" },
                    { 605, "rough" },
                    { 606, "round" },
                    { 607, "rub" },
                    { 608, "rule" },
                    { 609, "run" },
                    { 610, "sad" },
                    { 611, "safe" },
                    { 612, "sail" },
                    { 613, "salt" },
                    { 614, "same" },
                    { 615, "sand" },
                    { 616, "say" },
                    { 617, "scale" },
                    { 618, "school" },
                    { 619, "science" },
                    { 620, "scissors" },
                    { 621, "screw" },
                    { 622, "sea" },
                    { 623, "seat" },
                    { 624, "second" },
                    { 625, "secret" },
                    { 626, "secretary" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 627, "see" },
                    { 628, "seed" },
                    { 629, "seem" },
                    { 630, "selection" },
                    { 631, "self" },
                    { 632, "send" },
                    { 633, "sense" },
                    { 634, "separate" },
                    { 635, "serious" },
                    { 636, "servant" },
                    { 637, "sex" },
                    { 638, "shade" },
                    { 639, "shake" },
                    { 640, "shame" },
                    { 641, "sharp" },
                    { 642, "sheep" },
                    { 643, "shelf" },
                    { 644, "ship" },
                    { 645, "shirt" },
                    { 646, "shock" },
                    { 647, "shoe" },
                    { 648, "short" },
                    { 649, "shut" },
                    { 650, "side" },
                    { 651, "sign" },
                    { 652, "silk" },
                    { 653, "silver" },
                    { 654, "simple" },
                    { 655, "sister" },
                    { 656, "size" },
                    { 657, "skin" },
                    { 658, "" },
                    { 659, "skirt" },
                    { 660, "sky" },
                    { 661, "sleep" },
                    { 662, "slip" },
                    { 663, "slope" },
                    { 664, "slow" },
                    { 665, "small" },
                    { 666, "smash" },
                    { 667, "smell" },
                    { 668, "smile" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 669, "smoke" },
                    { 670, "smooth" },
                    { 671, "snake" },
                    { 672, "sneeze" },
                    { 673, "snow" },
                    { 674, "so" },
                    { 675, "soap" },
                    { 676, "society" },
                    { 677, "sock" },
                    { 678, "soft" },
                    { 679, "solid" },
                    { 680, "some" },
                    { 681, "son" },
                    { 682, "song" },
                    { 683, "sort" },
                    { 684, "sound" },
                    { 685, "soup" },
                    { 686, "south" },
                    { 687, "space" },
                    { 688, "spade" },
                    { 689, "special" },
                    { 690, "sponge" },
                    { 691, "spoon" },
                    { 692, "spring" },
                    { 693, "square" },
                    { 694, "stage" },
                    { 695, "stamp" },
                    { 696, "star" },
                    { 697, "start" },
                    { 698, "statement" },
                    { 699, "station" },
                    { 700, "steam" },
                    { 701, "steel" },
                    { 702, "stem" },
                    { 703, "step" },
                    { 704, "stick" },
                    { 705, "sticky" },
                    { 706, "stiff" },
                    { 707, "still" },
                    { 708, "stitch" },
                    { 709, "stocking" },
                    { 710, "stomach" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 711, "stone" },
                    { 712, "stop" },
                    { 713, "store" },
                    { 714, "story" },
                    { 715, "straight" },
                    { 716, "strange" },
                    { 717, "street" },
                    { 718, "stretch" },
                    { 719, "strong" },
                    { 720, "structure" },
                    { 721, "substance" },
                    { 722, "such" },
                    { 723, "sudden" },
                    { 724, "sugar" },
                    { 725, "suggestion" },
                    { 726, "summer" },
                    { 727, "sun" },
                    { 728, "support" },
                    { 729, "surprise" },
                    { 730, "sweet" },
                    { 731, "swim" },
                    { 732, "system" },
                    { 733, "table" },
                    { 734, "tail" },
                    { 735, "take" },
                    { 736, "talk" },
                    { 737, "tall" },
                    { 738, "taste" },
                    { 739, "tax" },
                    { 740, "teaching" },
                    { 741, "tendency" },
                    { 742, "test" },
                    { 743, "than" },
                    { 744, "that" },
                    { 745, "the" },
                    { 746, "then" },
                    { 747, "theory" },
                    { 748, "there" },
                    { 749, "thick" },
                    { 750, "thin" },
                    { 751, "thing" },
                    { 752, "this" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 753, "thought" },
                    { 754, "thread" },
                    { 755, "throat" },
                    { 756, "through" },
                    { 757, "thumb" },
                    { 758, "thunder" },
                    { 759, "ticket" },
                    { 760, "tight" },
                    { 761, "till" },
                    { 762, "time" },
                    { 763, "tin" },
                    { 764, "tired" },
                    { 765, "to" },
                    { 766, "toe" },
                    { 767, "together" },
                    { 768, "tomorrow" },
                    { 769, "tongue" },
                    { 770, "tooth" },
                    { 771, "top" },
                    { 772, "touch" },
                    { 773, "town" },
                    { 774, "trade" },
                    { 775, "train" },
                    { 776, "transport" },
                    { 777, "tray" },
                    { 778, "tree" },
                    { 779, "trick" },
                    { 780, "trouble" },
                    { 781, "trousers" },
                    { 782, "true" },
                    { 783, "turn" },
                    { 784, "twist" },
                    { 785, "umbrella" },
                    { 786, "under" },
                    { 787, "unit" },
                    { 788, "up" },
                    { 789, "use" },
                    { 790, "value" },
                    { 791, "verse" },
                    { 792, "very" },
                    { 793, "vessel" },
                    { 794, "view" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 795, "violent" },
                    { 796, "voice" },
                    { 797, "waiting" },
                    { 798, "walk" },
                    { 799, "wall" },
                    { 800, "war" },
                    { 801, "warm" },
                    { 802, "wash" },
                    { 803, "waste" },
                    { 804, "watch" },
                    { 805, "water" },
                    { 806, "wave" },
                    { 807, "wax" },
                    { 808, "way" },
                    { 809, "weather" },
                    { 810, "week" },
                    { 811, "weight" },
                    { 812, "well" },
                    { 813, "west" },
                    { 814, "wet" },
                    { 815, "wheel" },
                    { 816, "when" },
                    { 817, "where" },
                    { 818, "while" },
                    { 819, "whip" },
                    { 820, "whistle" },
                    { 821, "white" },
                    { 822, "who" },
                    { 823, "why" },
                    { 824, "wide" },
                    { 825, "will" },
                    { 826, "wind" },
                    { 827, "window" },
                    { 828, "wine" },
                    { 829, "wing" },
                    { 830, "winter" },
                    { 831, "wire" },
                    { 832, "wise" },
                    { 833, "with" },
                    { 834, "woman" },
                    { 835, "wood" },
                    { 836, "wool" }
                });

            migrationBuilder.InsertData(
                table: "Words",
                columns: new[] { "Id", "Value" },
                values: new object[,]
                {
                    { 837, "word" },
                    { 838, "work" },
                    { 839, "worm" },
                    { 840, "wound" },
                    { 841, "writing" },
                    { 842, "wrong" },
                    { 843, "year" },
                    { 844, "yellow" },
                    { 845, "yes" },
                    { 846, "yesterday" },
                    { 847, "you" },
                    { 848, "young" },
                    { 849, "bernhard" },
                    { 850, "breytenbach" },
                    { 851, "android" }
                });

            migrationBuilder.InsertData(
                table: "Games",
                columns: new[] { "Id", "PlayerId", "SecretWord", "Status" },
                values: new object[,]
                {
                    { 1, 1, "able", 1 },
                    { 2, 1, "baby", 2 },
                    { 3, 1, "cake", 1 },
                    { 4, 1, "damage", 0 },
                    { 5, 2, "ear", 1 },
                    { 6, 2, "face", 1 },
                    { 7, 3, "garden", 2 },
                    { 8, 3, "hair", 1 },
                    { 9, 3, "ice", 0 },
                    { 10, 4, "jelly", 1 }
                });

            migrationBuilder.InsertData(
                table: "Guesses",
                columns: new[] { "Id", "GameId", "IsRightGuess", "Letter" },
                values: new object[,]
                {
                    { 1, 1, true, "a" },
                    { 2, 1, true, "b" },
                    { 3, 1, true, "l" },
                    { 4, 1, true, "e" },
                    { 5, 2, true, "a" },
                    { 6, 2, false, "r" },
                    { 7, 2, false, "t" },
                    { 8, 2, false, "l" },
                    { 9, 2, false, "n" },
                    { 10, 2, false, "m" },
                    { 11, 2, false, "o" },
                    { 12, 3, true, "c" },
                    { 13, 3, true, "a" },
                    { 14, 3, true, "k" },
                    { 15, 3, true, "e" },
                    { 16, 4, true, "a" },
                    { 17, 5, true, "e" },
                    { 18, 5, true, "a" },
                    { 19, 5, true, "r" },
                    { 20, 5, false, "t" },
                    { 21, 6, true, "f" },
                    { 22, 6, true, "a" },
                    { 23, 6, true, "c" },
                    { 24, 6, true, "e" },
                    { 25, 7, false, "b" },
                    { 26, 7, false, "c" },
                    { 27, 7, false, "f" },
                    { 28, 7, false, "h" },
                    { 29, 7, false, "i" },
                    { 30, 7, false, "j" },
                    { 31, 8, true, "h" },
                    { 32, 8, true, "a" },
                    { 33, 8, true, "i" },
                    { 34, 8, true, "r" },
                    { 35, 9, true, "i" },
                    { 36, 10, true, "j" },
                    { 37, 10, true, "e" },
                    { 38, 10, true, "l" },
                    { 39, 10, true, "y" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Games_PlayerId",
                table: "Games",
                column: "PlayerId");

            migrationBuilder.CreateIndex(
                name: "IX_Guesses_GameId",
                table: "Guesses",
                column: "GameId");

            migrationBuilder.CreateIndex(
                name: "IX_Players_Name",
                table: "Players",
                column: "Name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Words_Value",
                table: "Words",
                column: "Value",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Guesses");

            migrationBuilder.DropTable(
                name: "Words");

            migrationBuilder.DropTable(
                name: "Games");

            migrationBuilder.DropTable(
                name: "Players");
        }
    }
}
